# Generated by Django 5.0.4 on 2024-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FaceRecognition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriminalImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("sketched_image", models.ImageField(upload_to="sketched_images/")),
                ("original_image", models.ImageField(upload_to="original_images/")),
            ],
        ),
    ]
