# Generated by Django 5.0.4 on 2024-04-19 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FaceRecognition", "0002_criminalimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminalimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
