# Generated by Django 5.0.4 on 2024-04-30 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FaceRecognition", "0003_criminalimage_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "feature",
                "verbose_name_plural": "features",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="FeatureOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="feature_options/")),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FaceRecognition.feature",
                    ),
                ),
            ],
        ),
    ]
